### ISSUE TITLE
B.D.E.1.1 Proposal

### ISSUE THREAD

**Issue by doloacu** [rsv-lineages/lineage-designation-B#1]
Hello! Below, I have listed the GISAID Accession IDs of sequences that could potentially belong to the B.D.E.1.1 clade:
EPI_ISL_19497475, EPI_ISL_19497497, EPI_ISL_19497476, EPI_ISL_19497498, EPI_ISL_19497473, EPI_ISL_19497495, EPI_ISL_19497474, EPI_ISL_19497496, EPI_ISL_19497471, EPI_ISL_19497493, EPI_ISL_19497472, EPI_ISL_19497494, EPI_ISL_19497491, EPI_ISL_19497470, EPI_ISL_19497492, EPI_ISL_19497479, EPI_ISL_19497477, EPI_ISL_19497499, EPI_ISL_19497478, EPI_ISL_19497490, EPI_ISL_19497464, EPI_ISL_19497486, EPI_ISL_19497465, EPI_ISL_19497487, EPI_ISL_19497462, EPI_ISL_19497484, EPI_ISL_19497463, EPI_ISL_19497485, EPI_ISL_19497482, EPI_ISL_19497483, EPI_ISL_19497480, EPI_ISL_19497481, EPI_ISL_19497505, EPI_ISL_19497506, EPI_ISL_19497503, EPI_ISL_19497504, EPI_ISL_19497468, EPI_ISL_19497501, EPI_ISL_19497469, EPI_ISL_19497502, EPI_ISL_19497466, EPI_ISL_19497488, EPI_ISL_19497467, EPI_ISL_19497489, EPI_ISL_19497500
All of them are from Argentina and belong to a monophyletic clade with good support in a phylogenetic tree alongside the reference sequences from github. The most important non-synonymous mutations are:
NS1:K74E
P:D225N
SH:I49M
G:L250P
F:N190S
F:N211S
L:N590S
L:K1759R

I am attaching the fasta file.
[RSV-B-20241021-GISAID.txt](https://github.com/user-attachments/files/17481704/RSV-B-20241021-GISAID.txt)
I look forward to your response. If there is anything I can improve, I hope you will let me know. I have tried to use the Autolin program, but I couldn't learn how to use it.
Thank you in advance.
Dolores Acuña

**Comment by doloacu** [comment]
@rneher I hope this message finds you well. Let me know if you need any additional information to make the analysis possible. I would like to know if my hypothesis is correct. Kind regards

**Comment by rneher** [comment]
@doloacu thanks a lot for making these issues and sorry it took so long to respond. This looks like a very sensible new lineage. We are currently in the process of scanning the tree of other possible lineages and will make a PR soon. It also looks like quite a few sequences from this group are available in genbank, so we can easily designate openly available representatives. 

I'll take a look at the other proposals as well!

thanks again!

**Comment by AngieHinrichs** [comment]
@rneher I have a B.D.E.1.1.yml ready for this, but I can't find the helper_scripts referred to in the README.md -- I will PR just the .yml for now.

**Comment by AngieHinrichs** [comment]
Oh wait, I guess it's these?  https://github.com/influenza-clade-nomenclature/helper-scripts ?  If so, I will add to the README too.

**Comment by rneher** [comment]
This lineage was added in https://github.com/AngieHinrichs/lineage-designation-B/commit/3710fee6f10acda93299aaed7cdca43b0f68dddc

**Comment by doloacu** [comment]
Dear Richard and Angie.
I have re-submitted the sequences to GenBank and GISAID because we had some errors in the script. The genomes are still a new lineage, but I noticed that the F:N190S mutation is no longer present in the new consensus genomes. Therefore, it would be better to correct the marked mutations of BDE11. I am available to help correct this error, and I hope you can excuse any inconvenience.
Best,
Dolores
